export const ASSIGNMENTS_FETCH_STARTED = 'ASSIGNMENTS_FETCH_STARTED';
export const ASSIGNMENTS_FETCH_COMPLETED = 'ASSIGNMENTS_FETCH_COMPLETED';
export const ASSIGNMENTS_FETCH_FAILED = 'ASSIGNMENTS_FETCH_FAILED';

export const ASSIGNMENT_ADD_STARTED = 'ASSIGNMENT_ADD_STARTED';
export const ASSIGNMENT_ADD_COMPLETED = 'ASSIGNMENT_ADD_COMPLETED';
export const ASSIGNMENT_ADD_FAILED = 'ASSIGNMENT_ADD_FAILED';

export const ASSIGNMENT_REMOVE_STARTED = 'ASSIGNMENT_REMOVE_STARTED';
export const ASSIGNMENT_REMOVE_COMPLETED = 'ASSIGNMENT_REMOVE_COMPLETED';
export const ASSIGNMENT_REMOVE_FAILED = 'ASSIGNMENT_REMOVE_FAILED';

export const ASSIGNMENT_UPDATE_STARTED = 'ASSIGNMENT_UPDATE_STARTED';
export const ASSIGNMENT_UPDATE_COMPLETED = 'ASSIGNMENT_UPDATE_COMPLETED';
export const ASSIGNMENT_UPDATE_FAILED = 'ASSIGNMENT_UPDATE_FAILED';