export const BOOKS_FETCH_STARTED = 'BOOKS_FETCH_STARTED';
export const BOOKS_FETCH_COMPLETED = 'BOOKS_FETCH_COMPLETED';
export const BOOKS_FETCH_FAILED = 'BOOKS_FETCH_FAILED';

export const BOOK_ADD_STARTED = 'BOOK_ADD_STARTED';
export const BOOK_ADD_COMPLETED = 'BOOK_ADD_COMPLETED';
export const BOOK_ADD_FAILED = 'BOOK_ADD_FAILED';

export const BOOK_REMOVE_STARTED = 'BOOK_REMOVE_STARTED';
export const BOOK_REMOVE_COMPLETED = 'BOOK_REMOVE_COMPLETED';
export const BOOK_REMOVE_FAILED = 'BOOK_REMOVE_FAILED';

export const BOOK_UPDATE_STARTED = 'BOOK_UPDATE_STARTED';
export const BOOK_UPDATE_COMPLETED = 'BOOK_UPDATE_COMPLETED';
export const BOOK_UPDATE_FAILED = 'BOOK_UPDATE_FAILED';