export const DELVAS_FETCH_STARTED = 'DELVAS_FETCH_STARTED';
export const DELVAS_FETCH_COMPLETED = 'DELVAS_FETCH_COMPLETED';
export const DELVAS_FETCH_FAILED = 'DELVAS_FETCH_FAILED';

export const DELVA_ADD_STARTED = 'DELVA_ADD_STARTED';
export const DELVA_ADD_COMPLETED = 'DELVA_ADD_COMPLETED';
export const DELVA_ADD_FAILED = 'DELVA_ADD_FAILED';

export const DELVA_REMOVE_STARTED = 'DELVA_REMOVE_STARTED';
export const DELVA_REMOVE_COMPLETED = 'DELVA_REMOVE_COMPLETED';
export const DELVA_REMOVE_FAILED = 'DELVA_REMOVE_FAILED';