export const EXAMS_FETCH_STARTED = 'EXAMS_FETCH_STARTED';
export const EXAMS_FETCH_COMPLETED = 'EXAMS_FETCH_COMPLETED';
export const EXAMS_FETCH_FAILED = 'EXAMS_FETCH_FAILED';

export const EXAM_ADD_STARTED = 'EXAM_ADD_STARTED';
export const EXAM_ADD_COMPLETED = 'EXAM_ADD_COMPLETED';
export const EXAM_ADD_FAILED = 'EXAM_ADD_FAILED';

export const EXAM_REMOVE_STARTED = 'EXAM_REMOVE_STARTED';
export const EXAM_REMOVE_COMPLETED = 'EXAM_REMOVE_COMPLETED';
export const EXAM_REMOVE_FAILED = 'EXAM_REMOVE_FAILED';