export const MATERIALS_FETCH_STARTED = 'MATERIALS_FETCH_STARTED';
export const MATERIALS_FETCH_COMPLETED = 'MATERIALS_FETCH_COMPLETED';
export const MATERIALS_FETCH_FAILED = 'MATERIALS_FETCH_FAILED';

export const MATERIAL_ADD_STARTED = 'MATERIAL_ADD_STARTED';
export const MATERIAL_ADD_COMPLETED = 'MATERIAL_ADD_COMPLETED';
export const MATERIAL_ADD_FAILED = 'MATERIAL_ADD_FAILED';

export const MATERIAL_REMOVE_STARTED = 'MATERIAL_REMOVE_STARTED';
export const MATERIAL_REMOVE_COMPLETED = 'MATERIAL_REMOVE_COMPLETED';
export const MATERIAL_REMOVE_FAILED = 'MATERIAL_REMOVE_FAILED';