export const PROVIDERS_FETCH_STARTED = 'PROVIDERS_FETCH_STARTED';
export const PROVIDERS_FETCH_COMPLETED = 'PROVIDERS_FETCH_COMPLETED';
export const PROVIDERS_FETCH_FAILED = 'PROVIDERS_FETCH_FAILED';

export const PROVIDER_ADD_STARTED = 'PROVIDER_ADD_STARTED';
export const PROVIDER_ADD_COMPLETED = 'PROVIDER_ADD_COMPLETED';
export const PROVIDER_ADD_FAILED = 'PROVIDER_ADD_FAILED';

export const PROVIDER_REMOVE_STARTED = 'PROVIDER_REMOVE_STARTED';
export const PROVIDER_REMOVE_COMPLETED = 'PROVIDER_REMOVE_COMPLETED';
export const PROVIDER_REMOVE_FAILED = 'PROVIDER_REMOVE_FAILED';

export const PROVIDER_UPDATE_STARTED = 'PROVIDER_UPDATE_STARTED';
export const PROVIDER_UPDATE_COMPLETED = 'PROVIDER_UPDATE_COMPLETED';
export const PROVIDER_UPDATE_FAILED = 'PROVIDER_UPDATE_FAILED';