export const SEMESTERS_FETCH_STARTED = 'SEMESTERS_FETCH_STARTED';
export const SEMESTERS_FETCH_COMPLETED = 'SEMESTERS_FETCH_COMPLETED';
export const SEMESTERS_FETCH_FAILED = 'SEMESTERS_FETCH_FAILED';

export const SEMESTER_ADD_STARTED = 'SEMESTER_ADD_STARTED';
export const SEMESTER_ADD_COMPLETED = 'SEMESTER_ADD_COMPLETED';
export const SEMESTER_ADD_FAILED = 'SEMESTER_ADD_FAILED';

export const SEMESTER_REMOVE_STARTED = 'SEMESTER_REMOVE_STARTED';
export const SEMESTER_REMOVE_COMPLETED = 'SEMESTER_REMOVE_COMPLETED';
export const SEMESTER_REMOVE_FAILED = 'SEMESTER_REMOVE_FAILED';