export const SSHIPEVENTS_FETCH_STARTED = 'SSHIPEVENTS_FETCH_STARTED';
export const SSHIPEVENTS_FETCH_COMPLETED = 'SSHIPEVENTS_FETCH_COMPLETED';
export const SSHIPEVENTS_FETCH_FAILED = 'SSHIPEVENTS_FETCH_FAILED';

export const SSHIPEVENT_ADD_STARTED = 'SSHIPEVENT_ADD_STARTED';
export const SSHIPEVENT_ADD_COMPLETED = 'SSHIPEVENT_ADD_COMPLETED';
export const SSHIPEVENT_ADD_FAILED = 'SSHIPEVENT_ADD_FAILED';

export const SSHIPEVENT_REMOVE_STARTED = 'SSHIPEVENT_REMOVE_STARTED';
export const SSHIPEVENT_REMOVE_COMPLETED = 'SSHIPEVENT_REMOVE_COMPLETED';
export const SSHIPEVENT_REMOVE_FAILED = 'SSHIPEVENT_REMOVE_FAILED';