export const TEACHER_FETCH_STARTED = 'TEACHER_FETCH_STARTED';
export const TEACHER_FETCH_COMPLETED = 'TEACHER_FETCH_COMPLETED';
export const TEACHER_FETCH_FAILED = 'TEACHER_FETCH_FAILED';

export const TEACHER_ADD_STARTED = 'TEACHER_ADD_STARTED';
export const TEACHER_ADD_COMPLETED = 'TEACHER_ADD_COMPLETED';
export const TEACHER_ADD_FAILED = 'TEACHER_ADD_FAILED';

export const TEACHER_REMOVE_STARTED = 'TEACHER_REMOVE_STARTED';
export const TEACHER_REMOVE_COMPLETED = 'TEACHER_REMOVE_COMPLETED';
export const TEACHER_REMOVE_FAILED = 'TEACHER_REMOVE_FAILED';
